import 'grapesjs/dist/css/grapes.min.css';
import grapesjs from 'grapesjs';
import grapesjsPresetWebpage from 'grapesjs-preset-webpage';
import grapesjsBlocksBasic from 'grapesjs-blocks-basic';
import grapesjsForms from 'grapesjs-plugin-forms';
import grapesjsCountdown from 'grapesjs-component-countdown';
import grapesjsExport from 'grapesjs-plugin-export';
import grapesjsTabs from 'grapesjs-tabs';
import grapesjsCustomCode from 'grapesjs-custom-code';
import grapesjsTouch from 'grapesjs-touch';
import grapesjsParserPostcss from 'grapesjs-parser-postcss';
import grapesjsTooltip from 'grapesjs-tooltip';
import grapesjsTuiImageEditor from 'grapesjs-tui-image-editor';
import grapesjsTyped from 'grapesjs-typed';
import grapesjsStyleBg from 'grapesjs-style-bg';

window.grapesjs = grapesjs;
window.grapesjsPresetWebpage = grapesjsPresetWebpage;
window.grapesjsBlocksBasic = grapesjsBlocksBasic;
window.grapesjsForms = grapesjsForms;
window.grapesjsCountdown = grapesjsCountdown;
window.grapesjsExport = grapesjsExport;
window.grapesjsTabs = grapesjsTabs;
window.grapesjsCustomCode = grapesjsCustomCode;
window.grapesjsTouch = grapesjsTouch;
window.grapesjsParserPostcss = grapesjsParserPostcss;
window.grapesjsTooltip = grapesjsTooltip;
window.grapesjsTuiImageEditor = grapesjsTuiImageEditor;
window.grapesjsTyped = grapesjsTyped;
window.grapesjsStyleBg = grapesjsStyleBg;